### ISSUE TITLE
Help with simple MIP

### ISSUE THREAD

**Issue by JockLawrie** [kul-forbes/StructuredOptimization.jl#11]
Hi there,

Very interesting package!

I am trying to get a simple linear binary integer program happening, with a view to building more complicated linear binary integer programs and comparing performance to existing solvers in JuMP.

I am having trouble with the most basic binary problem:
`Min c' * x such that x = (0, 1) and sum(x) == 1.`

Here's what I have so far:

```julia
using StructuredOptimization

n = 100
x = Variable(n)
c = rand(n)
@minimize ls(c' * x) st (norm(x) == 1, x == (0.0, 1.0))
```

The solution should be `x[i] == 1.0` where `c[i] == minimum(c)`.

The error I get is:

```julia
ERROR: Sorry, I cannot solve this problem
Stacktrace:
 [1] build(::Tuple{StructuredOptimization.Term{Int64,ProximalOperators.SqrNormL2{Float64},StructuredOptimization.Expression{1}},StructuredOptimization.Term{Int64,ProximalOperators.IndSphereL2{Float64},StructuredOptimization.Expression{1}},StructuredOptimization.Term{Int64,ProximalOperators.IndBinary{Float64,Float64},StructuredOptimization.Expression{1}}}, ::StructuredOptimization.PANOC) at /home/jock/.julia/v0.6/StructuredOptimization/src/solvers/build_solve.jl:53
 [2] solve(::Tuple{StructuredOptimization.Term{Int64,ProximalOperators.SqrNormL2{Float64},StructuredOptimization.Expression{1}},StructuredOptimization.Term{Int64,ProximalOperators.IndSphereL2{Float64},StructuredOptimization.Expression{1}},StructuredOptimization.Term{Int64,ProximalOperators.IndBinary{Float64,Float64},StructuredOptimization.Expression{1}}}, ::StructuredOptimization.PANOC) at /home/jock/.julia/v0.6/StructuredOptimization/src/solvers/build_solve.jl:119
```

Any ideas?

FYI, if I remove either constraint I get a solution (but not the one I'm looking for).

**Comment by nantonel** [comment]
Unfortunately this package was not thought for integer programming.

Your problem is not accepted because you have two constraints that are not separable. 
See [this section in the docs docs](https://kul-forbes.github.io/StructuredOptimization.jl/latest/tutorial.html#Limitations-1).

**Comment by JockLawrie** [comment]
OK thanks!

**Comment by panpat** [comment]
@nantonel It is easy to project on C={x| sum(x)=1, x\in {0,1}}. If we include this in ProximalOperators.jl then JockLawrie will be able to solve this problem at least.

**Comment by lostella** [comment]
Is it just: set the largest entry of x to 1, and the rest to 0? This makes me think: doesn’t the problem have an explicit solution? Just take the smallest entry of c and set the corresponding element of x to 1

**Comment by JockLawrie** [comment]
Thanks @panpat. No need to make the code more complex just for this case. I'm only experimenting and comparing to JuMP, which has a usable solution for this problem. Perhaps just some documentation that more clearly sets out what problems are suited to this package?

@lostella Yes the solution in this case is known in advance, which is why I started with this problem - I know what result should be returned.

Thanks again!

**Comment by nantonel** [comment]
I think it would be nice to add some API for the user to be able to define its own function or constraint. 

It is currently possible to do that anyway: 
```julia
using StructuredOptimization, ProximalOperators

# create new ProximalOperators  object
immutable MyInd <: ProximableFunction 
... #some parameters
end

# define your indicator function/function
function (f::MyInd){T <: Real}(x::AbstractArray{T})
...
end

# define projection/prox
function ProximalOperators.prox!(y, f::MyInd, x, gamma::Real=1.0)
...
end

# define StructuredOptimization term
function myind(ex::StructuredOptimization.AbstractExpression)
    return StructuredOptimization.Term(MyInd(), ex)
end

n = 100
x = Variable(n)
...
@minimize ... st myind(x)
```
But it would be very nice to have a more user friendly interface for this.

**Comment by nantonel** [comment]
@JockLawrie 

for your case: 
```julia
using StructuredOptimization, ProximalOperators

immutable MyInd <: ProximableFunction end

# define indicator function
function (f::MyInd){T <: Real}(x::AbstractArray{T})
  f = zero(T)
  for k in eachindex(x)
    if x[k] != 0.0 || x[k] != 1.0
      return +Inf
    end
    f += x[k]
  end
  if f == 1.0
      return 0.0
  else
      return +Inf
  end
end

# define projection
function ProximalOperators.prox!(y, f::MyInd, x, gamma::Real=1.0)
    idx = indmax(x)
    for i in eachindex(x)
        y[i] = idx == i ? 1.0 : 0.0
    end
    return 0.0
end

function myind(ex::StructuredOptimization.AbstractExpression)
    return StructuredOptimization.Term(MyInd(), ex)
end

srand(1)
n = 100
x = Variable(rand(n))
c = rand(n)
@minimize ls(c'*x) st myind(x)
```                             
Notice that I haven't really tested everything properly!
