### ISSUE TITLE
Doesn't work in Julia 1.1.1

### ISSUE THREAD

**Issue by patwa67** [kul-forbes/StructuredOptimization.jl#22]
The following code worked fine in 1.0.1, but no longer in 1.1.1:
```
using StructuredOptimization

#Simulated data (n observations, p variables, tr true variables, sig error)
n, p, q, tr_p1, tr_p2, sig = 5000, 10000, 2, 10, 5, 0.1
X = randn(n, p)
Y = randn(n, q)
b_true1 = [randn(tr_p1)..., zeros(p-tr_p1)...]
b_true2 = [randn(tr_p2)..., zeros(p-tr_p2)...]
y1 = X*b_true1 + sig*randn(n)
y2 = X*b_true2 + sig*randn(n)
Y[:,1] = y1
Y[:,2] = y2
Xtrain = X[1:4000,:]
Xtest = X[4001:5000,:]
Ytrain = Y[1:4000,:]
Ytest = Y[4001:5000,:]

b0 = Variable(p,q)            
λ = 0.001*norm(Xtrain'*Ytrain,Inf)
@minimize ls(Xtrain*b0 - Ytrain) + λ*norm(b0,0) with ZeroFPR;# solve problem
```

Gives me the following error:
julia> @minimize ls(Xtrain*b0 - Ytrain) + λ*norm(b0,0) with ZeroFPR
ERROR: MethodError: no method matching solve(::Tuple{StructuredOptimization.Term{Int64,ProximalOperators.SqrNormL2{Float64},StructuredOptimization.Expression{1,AbstractOperators.AffineAdd{AbstractOperators.MatrixOp{Float64,Float64,Array{Float64,2}},Array{Float64,2},false}}},StructuredOptimization.Term{Float64,ProximalOperators.NormL0{Float64},StructuredOptimization.Expression{1,AbstractOperators.Eye{Float64,2}}}}, ::Type{ZeroFPR})
Closest candidates are:
  solve(::Tuple, ::Union{ForwardBackward, PANOC, ZeroFPR}) at /home/pawn0002/.julia/packages/StructuredOptimization/ocilJ/src/solvers/build_solve.jl:74
Stacktrace:
 [1] top-level scope at none:0

**Comment by nantonel** [comment]
We've recently updated the solvers API, the following command works on Julia 1.1.1
```julia
@minimize ls(Xtrain*b0 - Ytrain) + λ*norm(b0,0) with ZeroFPR()
```
