### ISSUE TITLE
Quadratic form in LS loss function

### ISSUE THREAD

**Issue by patwa67** [kul-forbes/StructuredOptimization.jl#24]
I have the following example of the multi-task LASSO:
```
using StructuredOptimization, ProximalAlgorithms, Statistics

#Simulated data (n observations, p variables, tr true variables, sig error)
n, p, q, tr_p1, tr_p2, sig = 500, 1000, 2, 10, 5, 0.1
X = randn(n, p)
Y = randn(n, q)
b_true1 = [randn(tr_p1)..., zeros(p-tr_p1)...]
b_true2 = [randn(tr_p2)..., zeros(p-tr_p2)...]
y1 = X*b_true1 + sig*randn(n)
y2 = X*b_true2 + sig*randn(n)
Y[:,1] = y1
Y[:,2] = y2
B = Variable(p,q)
lambda = 0.001*norm(X'*Y,Inf)
#Multi-task LASSO
@minimize ls(X*B - Y) + lambda*norm(B,1) with ZeroFPR();# solve problem
Bhat = copy(~B)
```

As I understand, the ls() loss function becomes the Frobenius loss in this case. Is it possible to construct a new loss function that takes the covariance between Y[:,1] and Y[:,2] into account, for example using a quadratic form?

**Comment by nantonel** [comment]
`ls(x)` is a short hand of `0.5*norm(x)^2` which is equivalent to `0.5*x'*x`.
 
(Notice that `0.5*x'*x` won't work in StructuredOptimization.)  

I guess you want something like `1/2*x'*A*x`? Weighted norm should do the job:
```julia
 ls(W*x) 
```
where `A = W'*W`.

But I'm not sure of what cost function you're looking for.

**Comment by patwa67** [comment]
Is ```A = W' * W``` the Cholesky decomposition?

**Comment by nantonel** [comment]
No `A=W'*W` is just an equality. If you tell me the mathematical expression of the cost function you're interested in then we can see if it's possible to realise it with StructOpt.

**Comment by patwa67** [comment]
Well, that's one of the problems, I don't know what it should look like. It is the standard Frobenius norm as loss function ```ls(X*B - Y)```, but this one only treats the columns within X*B and Y as independent. In statistical terms this means that the residual covariance is assumed to be zero (or actually independent). I want to incorporate the residual covariance into the loss function, it's not needed in the penalty function. I think your suggestion about a weighted norm is on the right track, but in some way ```x``` needs to be replaced with the multivariate ```X*B - Y```.

**Comment by patwa67** [comment]
There are two different weighted Frobenius norms in (1.2) and (1.3) in the following paper:
https://www.maths.manchester.ac.uk/~higham/narep/narep369.pdf

**Comment by nantonel** [comment]
You can use both representations:
```julia
ls(H .* (X) )
```
and
```julia
ls(W*(X)*W')
```
However I don't really know what you should put inside the weights.
