### ISSUE TITLE
In the documentation, many (but not all) latex formulas fail to display.

### ISSUE THREAD

**Issue by reumle** [kul-forbes/StructuredOptimization.jl#30]
That might be an issue about "documenter"…. and is not only for your repo. Other Julia optimisation documentation also have that problem.

For instance, this equation fails to render: It is under `quick tutorial` then `constrained optimization`
\[\begin{align*} \underset{ \mathbf{x} }{\text{minimize}} \ & \tfrac{1}{2} \| \mathbf{x} * \mathbf{h} - \mathbf{y} \|^2 \\ \text{subject to} \ & \mathbf{x} \geq 0 \end{align*}\]

Newbie here, cannot help much more, good luck!

**Comment by nantonel** [comment]
Seems like this is happening only on [dev documentation](https://kul-forbes.github.io/StructuredOptimization.jl/dev/tutorial/#Constrained-optimization-1) not on the [stable](https://kul-forbes.github.io/StructuredOptimization.jl/stable/tutorial/#Constrained-optimization-1).

Most likely a problem of documenter.

**Comment by nantonel** [comment]
Ok, it's fixed now! I didn't really find out what the problem was... just rearranged the broken equations a bit and now they render properly!
