### ISSUE TITLE
New release with new compat bounds?

### ISSUE THREAD

**Issue by baggepinnen** [kul-forbes/StructuredOptimization.jl#33]
Hello! Would it be possible to make a new release of this package with updated compat bounds for some of the dependencies? Currently, the `Project.toml` file lists deps without upper compat bound, i.e.,
```
AbstractOperators = "≥ 0.1.0"DSP = "≥ 0.5.1"FFTW = "≥ 0.2.4"ProximalAlgorithms = "≥ 0.3.0"ProximalOperators = "≥ 0.8.0"RecursiveArrayTools = "≥ 0.18.0"
```
This is no longer accepted in the general registry, so when installing this package, a long list of packages get downgraded to very old versions. To see the actual compat boudns that will be used for this package, see the compat file in general
https://github.com/JuliaRegistries/General/blob/master/S/StructuredOptimization/Compat.toml

**Comment by lostella** [comment]
I think that’s absolutely something to do, thanks for pointing that out
